# Generated by cgrade: these are the exact flags used for grading.
CC = gcc
CFLAGS = -std=c11 -Wall -Wextra -Werror
LDLIBS = 

hw1: hw1.c
	$(CC) $(CFLAGS) -o hw1 hw1.c $(LDLIBS)

test: hw1
	python3 tests/run_tests.py --no-build

zip:
	python3 tests/make_zip.py $(ID)

clean:
	rm -f hw1 hw1.exe *.o *.zip

.PHONY: test zip clean
